# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    pagination:
        class: NewsBundle\Services\Pagination
        arguments: [ "@doctrine.orm.entity_manager" ]

    app.images_uploader:
        class: NewsBundle\Services\ImageUploader
        arguments: ["%images_directory%"]

    app.exception_listener:
        class: NewsBundle\Services\RedirectUserListener
        arguments:
                    - "@router"
        tags:
            - { name: kernel.event_listener, event: kernel.exception }