<?php

namespace NewsBundle\Repository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        return parent::findAll();
    }

    public function updateEntity($news)
    {
        $q = $this->createQueryBuilder('n')
            ->update('NewsBundle:News', 'n')
            ->set('n.header', '?1')
            ->set('n.description', '?2')
            ->set('n.text', '?3')
            ->setParameters(array(1 => $news->getHeader(), 2 => $news->getDescription(), 3 => $news->getText()))
            ->where('n.id = ?4')
            ->setParameter(4, $news->getId())
            ->getQuery();
        $q -> execute();
    }
}
